### ISSUE TITLE
Enforce basic auth

### ISSUE THREAD

**Issue by alexellis** [openfaas/faas-swarm#31]
## Expected Behaviour

No calls should be possible to the `/system/*` routes for the providers unless decorated with basic auth. Note that the gateway has more endpoints than the provider and not all endpoints are proxied. 

## Current Behaviour

The gateway is protected, but not faas-swarm.

This is not a problem for external access since only the gateway is exposed, but internal functions could invoke the endpoints since Swarm gives no way of providing NetworkPolicy.

This change must only become active when basic auth is enabled. 

## Possible Solution

* Update openfaas/faas gateway to pass credentials to the provider
* Update faas-swarm to bind the same basic auth secrets as the gateway
* Update faas-swarm to validate basic auth using the library added/created for openfaas/faas gateway

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

**Comment by burtonr** [comment]
I'll take a look this weekend

**Comment by burtonr** [comment]
Diving in to this, I realize there is a need to separate the auth code from the `faas` project. Essentially, we want to perform the same checks that the gateway is performing within the `faas-swarm` provider. Of course, this isn't limited to Swarm. Other providers could need, or want, those additional checks in place.

I'm thinking of moving the `load_credentials.go` and `basic_auth.go` to the `faas-provider` package. `load_credentials includes the `BasicAuthCredentials` and `ReadBasicAuth` types, while `basic_auth.go` includes the `DecorateWithBasicAuth()` call that validates the credentials.

I'm not certain this is the best solution though. Doing that would mean the gateway would also need reference to the `faas-provider` package, although it isn't really a provider...

An option is to copy, rather than move, the auth code to the provider. Although, just using the word _copy_ makes me shudder just a little bit :)

Another option would be to create a new package `faas-auth` or `faas-security` (or something else) that would only contain the auth code. This could then be utilized by both the individual providers as well as the gateway without causing confusion, or duplicating code. 

What are your thoughts @alexellis?

**Comment by alexellis** [comment]
Feedback given on https://github.com/openfaas/faas-provider/pull/7 @burtonr

**Comment by alexellis** [comment]
This change must only become active when basic auth is enabled.

**Comment by burtonr** [comment]
Yes, part of this change will be to add the `basic_auth` and `secret_mount_path` to the `faas-swarm` environment variables as well as adding the `secrets` in the `docker-compose.yml` (and `armhf.yml`). 

Those updated will need to be another PR to the faas project when the faas-swarm version gets updated to include the auth checking changes. A lot of coordination needs to happen for this!

**Comment by alexellis** [comment]
Derek close: fixed in 0.4.2
